services:
  budgetmanager.service:
    image: budgetmanager.service
    build:
      context: .
      dockerfile: BudgetManager.Service.Api/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
